#!/bin/sh

echo "setting up proxy..."

proxy='http://proxy.ssn.net:8080'

echo "small..."
export http_proxy=$proxy
export https_proxy=$proxy
export ftp_proxy=$proxy
echo "large..."
export HTTP_PROXY=$proxy
export HTTPS_PROXY=$proxy
export FTP_PROXY=$proxy
sock='socks://proxy.ssn.net:8080'
echo "all..."
export all_proxy=$sock
export ALL_PROXY=$sock
echo "setting bypass..."
noprox='localhost,127.0.0.0/8,::1,lms.ssn.edu.in,*.ssn.net'
export no_proxy=$noprox

echo "Enter 1 if it's the first time applying proxy..."

read vari

if [ $vari -eq 1 ]
 then
sudo bash sudo_applier
else
echo "preuser config..."
fi

echo $(env | grep "proxy")

echo "done..."

